const en = {
  title: 'Language environments', runTitle: 'Run a program', close: 'Close', refresh: 'Refresh',
  intro: 'Use Python, Java, Go, Rust, Bun or Node.js on demand. The agent can install packages for a task with your allowed permissions. You can also install, import or delete them here.',
  empty: 'No package is published for this language yet. Import a compatible .rishenv file or add its HTTPS URL.',
  unavailable: 'Language environments are not available in this version on this device.',
  loading: 'Loading environments…', install: 'Install', remove: 'Delete', select: 'Choose', selected: 'Selected',
  importFile: 'Import .rishenv file', addURL: 'Add from URL', urlPlaceholder: 'https://…/language.rishenv',
  urlHelp: 'Use a direct HTTPS link to a .rishenv package. Sign-in links are not supported.',
  invalidURL: 'Enter a valid HTTPS package URL without credentials or a fragment.',
  not_installed: 'Not installed', downloading: 'Downloading', installing: 'Installing', installed: 'Installed', failed: 'Failed',
  cancel: 'Cancel download', busy: 'Working…', error: 'The operation could not finish.',
  cancelled: 'Cancelled', run: 'Run', stop: 'Stop', starting: 'Starting', running: 'Running', stopping: 'Stopping', completed: 'Finished',
  snapshot: 'Runs a copy of your workspace files. Files created or changed by the program are not written back to your project. Closing this panel or leaving the app stops the run.',
  entry: 'Entry file', entryPlaceholder: 'src/main.py', entryHelp: 'Enter a path relative to this workspace, such as main.py or src/main.rs.',
  args: 'Arguments (JSON array)', argsHelp: 'Each string is one literal argument. No shell expansion. Example: ["hello world", "--port", "8080"]',
  invalidEntry: 'Use a relative file path without empty, . or .. segments.', invalidArgs: 'Enter a JSON array of up to 64 strings.',
  needWorkspace: 'Open a workspace to run a program.', needEnvironment: 'Choose a language environment before running.',
  chooseEnvironment: 'Environment', preparing: 'Preparing workspace…', downloadingSelected: 'Installing the selected environment…',
  blocked: 'Finish the current task or save recovery before starting a program.',
  output: 'Standard output', errors: 'Standard error', noOutput: 'No output yet.', truncated: 'Output limit reached; only the first 256 KB is shown.',
  exitCode: 'Exit code', memory: 'Memory', packageSize: 'Disk', runUnavailable: 'Program execution is not available in this version on this device.',
  selectedOnDemand: 'If this environment is not installed, Run downloads only the selected package.',
  javaSourceBudget: 'Compiling Java source can take several minutes. This run has a 20-minute limit and can be stopped at any time.',
  localOnly: 'No model API key is required.', rootStale: 'This workspace changed. Reopen the run panel and try again.',
  removePrompt: 'Delete this environment from the device?', confirmDelete: 'Delete environment', keep: 'Keep',
  installFailed: 'Installation failed. You can retry or import another package.',
};
const zh: typeof en = {
  title: '语言运行环境', runTitle: '运行程序', close: '关闭', refresh: '刷新',
  intro: '按需使用 Python、Java、Go、Rust、Bun 或 Node.js。智能体可按任务需要和已授予的权限安装环境，你也可以在这里手动安装、导入或删除。',
  empty: '这个语言还没有已发布的环境包。可以导入兼容的 .rishenv 文件，或添加 HTTPS 下载地址。',
  unavailable: '当前设备上的这个版本暂不支持语言运行环境。',
  loading: '正在读取运行环境…', install: '安装', remove: '删除', select: '选择', selected: '已选择',
  importFile: '导入 .rishenv 文件', addURL: '从链接添加', urlPlaceholder: 'https://…/language.rishenv',
  urlHelp: '请输入 .rishenv 环境包的 HTTPS 直链，暂不支持需要登录的链接。',
  invalidURL: '请输入有效的 HTTPS 环境包链接，不含账号密码或片段标识。',
  not_installed: '未安装', downloading: '正在下载', installing: '正在安装', installed: '已安装', failed: '失败',
  cancel: '取消下载', busy: '正在处理…', error: '操作未能完成。',
  cancelled: '已取消', run: '运行', stop: '停止', starting: '正在启动', running: '运行中', stopping: '正在停止', completed: '已结束',
  snapshot: '本次运行使用工作区文件的副本。程序创建或修改的文件不会写回项目。关闭此面板或离开应用会停止运行。',
  entry: '入口文件', entryPlaceholder: 'src/main.py', entryHelp: '填写相对于当前工作区的路径，例如 main.py 或 src/main.rs。',
  args: '参数（JSON 数组）', argsHelp: '每个字符串作为一个原样参数，不进行 shell 展开。例如：["hello world", "--port", "8080"]',
  invalidEntry: '请使用相对文件路径，不含空路径段、. 或 ..。', invalidArgs: '请输入最多包含 64 个字符串的 JSON 数组。',
  needWorkspace: '请先打开工作区，再运行程序。', needEnvironment: '请先选择语言运行环境。',
  chooseEnvironment: '运行环境', preparing: '正在准备工作区…', downloadingSelected: '正在安装所选运行环境…',
  blocked: '请先完成当前任务或保存恢复，再运行程序。',
  output: '标准输出', errors: '错误输出', noOutput: '暂无输出。', truncated: '输出已达上限，仅显示前 256 KB。',
  exitCode: '退出码', memory: '内存', packageSize: '磁盘', runUnavailable: '当前设备上的这个版本暂不支持运行程序。',
  selectedOnDemand: '未安装的环境会在点击运行时按需下载，仅下载当前选择的环境。',
  javaSourceBudget: 'Java 源码编译可能需要数分钟。本次最长运行 20 分钟，可随时停止。',
  localOnly: '无需配置模型 API key。', rootStale: '工作区已变更，请重新打开运行面板后重试。',
  removePrompt: '从本机删除这个运行环境？', confirmDelete: '删除运行环境', keep: '保留',
  installFailed: '安装失败，可以重试或导入其他环境包。',
};
export const runtimeCopy = (locale: string) => locale.startsWith('zh') ? zh : en;
export const familyNames = { python: 'Python', java: 'Java', go: 'Go', rust: 'Rust', bun: 'Bun', node: 'Node.js' } as const;
export function environmentBytes(bytes: number): string {
  return bytes < 1048576 ? `${(bytes / 1024).toFixed(0)} KB` : bytes < 1073741824
    ? `${(bytes / 1048576).toFixed(1)} MB` : `${(bytes / 1073741824).toFixed(1)} GB`;
}
