//! Canonical JSON (RFC 8785 / JCS) and the domain-separated hashes built on
//! it, matching the Objective-C++ implementation in
//! `modules/rish/ios/Sources/DSHWorkspaceCanonical.mm` and the `DSHAgentHJ` /
//! `DSHAgentHB` helpers in `AgentNativeWAL.mm` byte for byte.
//!
//! The iOS engine's persisted digests, CAS tokens and receipts all derive
//! from these bytes, so this module is pinned by
//! `modules/rish/core/fixtures/canonical-golden.json`, generated by the
//! Objective-C code itself (`AgentCoreGoldenTests.mm`).

use serde_json::Value;
use sha2::{Digest, Sha256};
use std::fmt::Write as _;

/// Largest integer magnitude the bridge can carry exactly (2^53 - 1).
pub const MAX_SAFE_INTEGER: u64 = 9_007_199_254_740_991;
/// Nesting depth beyond which the encoder refuses, as the ObjC encoder does.
pub const MAX_DEPTH: usize = 64;

/// Why a value could not be canonicalised. Value-free by construction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CanonicalError {
    /// A number is non-finite, negative zero, or an integer outside the safe range.
    Number,
    /// Nesting deeper than [`MAX_DEPTH`].
    Depth,
}

/// Serialises `value` as canonical JSON bytes: UTF-8, no BOM, no trailing
/// newline, object keys sorted by UTF-16 code units, numbers in ECMAScript
/// shortest form, strings escaping only `"`, `\` and controls below U+0020.
pub fn canonical_json(value: &Value) -> Result<Vec<u8>, CanonicalError> {
    let mut out = String::new();
    append_value(value, &mut out, 0)?;
    Ok(out.into_bytes())
}

fn append_value(value: &Value, out: &mut String, depth: usize) -> Result<(), CanonicalError> {
    if depth > MAX_DEPTH {
        return Err(CanonicalError::Depth);
    }
    match value {
        Value::Null => out.push_str("null"),
        Value::Bool(true) => out.push_str("true"),
        Value::Bool(false) => out.push_str("false"),
        // With serde_json's arbitrary_precision the lexeme survives parsing,
        // so an integer lexeme (including "-0", which NSJSONSerialization
        // decodes as the integer 0) takes the integer path exactly as an
        // integer-typed NSNumber does, and only decimal/exponent lexemes go
        // through the double formatter.
        Value::Number(number) => {
            if let Some(unsigned) = number.as_u64() {
                if unsigned > MAX_SAFE_INTEGER {
                    return Err(CanonicalError::Number);
                }
                write!(out, "{unsigned}").expect("string write");
            } else if let Some(signed) = number.as_i64() {
                if signed.unsigned_abs() > MAX_SAFE_INTEGER {
                    return Err(CanonicalError::Number);
                }
                write!(out, "{signed}").expect("string write");
            } else if !number.is_f64() {
                // An integer lexeme too large for 64 bits. NSJSONSerialization
                // would decode it as a lossy double; the core refuses it, since
                // no safe integer or engine-written value ever looks like this.
                return Err(CanonicalError::Number);
            } else {
                let floating = number.as_f64().ok_or(CanonicalError::Number)?;
                out.push_str(&canonical_number(floating)?);
            }
        }
        Value::String(text) => append_string(text, out),
        Value::Array(items) => {
            out.push('[');
            for (index, item) in items.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                append_value(item, out, depth + 1)?;
            }
            out.push(']');
        }
        Value::Object(map) => {
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort_by(|left, right| utf16_units(left).cmp(utf16_units(right)));
            out.push('{');
            for (index, key) in keys.iter().enumerate() {
                if index > 0 {
                    out.push(',');
                }
                append_string(key, out);
                out.push(':');
                append_value(&map[*key], out, depth + 1)?;
            }
            out.push('}');
        }
    }
    Ok(())
}

fn utf16_units(text: &str) -> impl Iterator<Item = u16> + '_ {
    text.encode_utf16()
}

/// ECMAScript `Number::toString` for a finite, non-negative-zero double:
/// shortest round-trip digits, fixed notation when the decimal exponent is in
/// `[-6, 21)`, otherwise `d.ddde±x`.
pub fn canonical_number(value: f64) -> Result<String, CanonicalError> {
    if !value.is_finite() || (value == 0.0 && value.is_sign_negative()) {
        return Err(CanonicalError::Number);
    }
    if value == 0.0 {
        return Ok("0".to_string());
    }
    // The ObjC formatter round-trips candidates through istringstream, which
    // reports underflow for subnormal results and therefore never accepts a
    // subnormal double. Refuse them the same way.
    if !value.is_normal() {
        return Err(CanonicalError::Number);
    }
    // `{:e}` yields the shortest digit string that round-trips, as
    // `d.ddde±x`; the ObjC side derives the same digits by probing
    // precisions 1..=17. Both then apply the ECMAScript layout below.
    let scientific = format!("{:e}", value.abs());
    let (mantissa, exponent) = scientific.split_once('e').expect("scientific form");
    let exponent: i64 = exponent.parse().expect("exponent");
    let digits: String = mantissa.chars().filter(|c| *c != '.').collect();
    let decimal_position = exponent + 1; // value = 0.digits * 10^decimal_position
    let mut result = String::new();
    if (-6..21).contains(&exponent) {
        if decimal_position <= 0 {
            result.push_str("0.");
            for _ in 0..(-decimal_position) {
                result.push('0');
            }
            result.push_str(&digits);
        } else if decimal_position as usize >= digits.len() {
            result.push_str(&digits);
            for _ in 0..(decimal_position as usize - digits.len()) {
                result.push('0');
            }
        } else {
            result.push_str(&digits[..decimal_position as usize]);
            result.push('.');
            result.push_str(&digits[decimal_position as usize..]);
        }
    } else {
        result.push_str(&digits[..1]);
        if digits.len() > 1 {
            result.push('.');
            result.push_str(&digits[1..]);
        }
        result.push('e');
        if exponent >= 0 {
            result.push('+');
        }
        write!(result, "{exponent}").expect("string write");
    }
    if value.is_sign_negative() {
        result.insert(0, '-');
    }
    Ok(result)
}

fn append_string(text: &str, out: &mut String) {
    out.push('"');
    for character in text.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\u{8}' => out.push_str("\\b"),
            '\u{c}' => out.push_str("\\f"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                write!(out, "\\u{:04x}", c as u32).expect("string write");
            }
            c => out.push(c),
        }
    }
    out.push('"');
}

/// Lowercase hexadecimal SHA-256 of `bytes` (`DSHWorkspaceSHA256Hex`).
pub fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut hex = String::with_capacity(64);
    for byte in digest {
        write!(hex, "{byte:02x}").expect("string write");
    }
    hex
}

/// A hash domain tag: 1..=128 bytes of UTF-8 with no NUL, as
/// `DSHAgentBoundedUTF8String(tag, 128, NO, …)` accepts.
fn valid_tag(tag: &str) -> bool {
    !tag.is_empty() && tag.len() <= 128 && !tag.contains('\0')
}

/// The domain prefix both hash helpers use: `rish.<tag>.v1` followed by NUL.
fn domain_prefix(tag: &str) -> Vec<u8> {
    let mut prefix = Vec::with_capacity(tag.len() + 9);
    prefix.extend_from_slice(b"rish.");
    prefix.extend_from_slice(tag.as_bytes());
    prefix.extend_from_slice(b".v1\0");
    prefix
}

/// `DSHAgentHJ`: SHA-256(`rish.<tag>.v1\0` || canonical JSON of `value`).
pub fn hash_json(tag: &str, value: &Value) -> Option<String> {
    if !valid_tag(tag) {
        return None;
    }
    let mut input = domain_prefix(tag);
    input.extend_from_slice(&canonical_json(value).ok()?);
    Some(sha256_hex(&input))
}

/// `DSHAgentHB`: SHA-256(`rish.<tag>.v1\0` || big-endian u64 length || bytes).
pub fn hash_bytes(tag: &str, bytes: &[u8]) -> Option<String> {
    if !valid_tag(tag) {
        return None;
    }
    let mut input = domain_prefix(tag);
    input.extend_from_slice(&(bytes.len() as u64).to_be_bytes());
    input.extend_from_slice(bytes);
    Some(sha256_hex(&input))
}

#[cfg(test)]
mod tests {
    use super::*;

    // ECMAScript Number::toString expectations, independent of the golden.
    #[test]
    fn numbers_follow_ecmascript_layout() {
        let cases: &[(f64, &str)] = &[
            (0.0, "0"),
            (1.0, "1"),
            (-1.0, "-1"),
            (1.5, "1.5"),
            (100.0, "100"),
            (0.1, "0.1"),
            (0.30000000000000004, "0.30000000000000004"),
            (1e20, "100000000000000000000"),
            (1e21, "1e+21"),
            (123456789012345680000.0, "123456789012345680000"),
            (0.000001, "0.000001"),
            (1e-7, "1e-7"),
            (1.7976931348623157e308, "1.7976931348623157e+308"),
            (-2.5, "-2.5"),
            (9007199254740991.0, "9007199254740991"),
        ];
        for (value, expected) in cases {
            assert_eq!(canonical_number(*value).unwrap(), *expected, "{value:?}");
        }
        assert_eq!(canonical_number(-0.0), Err(CanonicalError::Number));
        assert_eq!(canonical_number(5e-324), Err(CanonicalError::Number));
        assert_eq!(
            canonical_number(f64::MIN_POSITIVE),
            Ok("2.2250738585072014e-308".to_string())
        );
        assert_eq!(canonical_number(f64::NAN), Err(CanonicalError::Number));
        assert_eq!(canonical_number(f64::INFINITY), Err(CanonicalError::Number));
    }

    #[test]
    fn keys_sort_by_utf16_units_and_strings_escape_minimally() {
        let value: Value =
            serde_json::from_str(r#"{"\ufb01":1,"\ud83d\ude00":2,"z":3,"a\nb":"\u0001\u007f"}"#)
                .unwrap();
        let text = String::from_utf8(canonical_json(&value).unwrap()).unwrap();
        assert_eq!(
            text,
            "{\"a\\nb\":\"\\u0001\u{7f}\",\"z\":3,\"\u{1F600}\":2,\"\u{FB01}\":1}"
        );
    }

    #[test]
    fn hashes_use_the_domain_prefix() {
        let expected = sha256_hex(b"rish.golden.v1\0{}");
        assert_eq!(
            hash_json("golden", &Value::Object(Default::default())).unwrap(),
            expected
        );
        let mut preimage = b"rish.t.v1\0".to_vec();
        preimage.extend_from_slice(&3u64.to_be_bytes());
        preimage.extend_from_slice(b"abc");
        assert_eq!(hash_bytes("t", b"abc").unwrap(), sha256_hex(&preimage));
        assert!(hash_json("", &Value::Null).is_none());
    }
}
